name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run test.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests and save output
        run: |
          node --test test.js > test-output.txt 2>&1 || echo "Tests completed with exit code $?"
          # Save the exit code for later use
          echo "EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-output.txt

      - name: Fail if tests failed
        if: env.EXIT_CODE != '0'
        run: exit 1
